### PR TITLE
fixed it jit 

### PR DESCRIPTION
**Pull request by EthanFalcao**

### CODE REVIEW

**Comment by syedshazli** [comment]
Do not spread lies on the internet rangeesh

**Review by syedshazli — CHANGES_REQUESTED** [review]
Cap

**Comment by syedshazli** [comment]
thanks sir rangeesh

**Comment by EthanFalcao** [comment]
jit, heads gonna look at your bio and think you need a visa,

**Comment by syedshazli** [comment]
Lmaoo I aint even think of that bruh

**Comment by syedshazli** [comment]
[image: image.png]
People wanna do ur project the most. What do you think?

**Comment by EthanFalcao** [comment]
Im done, there is  a lot to do for each project. How many heads?

**Comment by syedshazli** [comment]
Seems like we got 15 people. I think we all focus together on one and if we
done on time we can do another. Or we could have 3 different project
managers and make 3 different projects for smaller group sizes. My friend
Artem is pretty experienced with this stuff I sent him ur IG as wel he is
going to get in contact on discord too. Quality over quantity as they say
so what are your thoughts.

**Comment by EthanFalcao** [comment]
i think we should split into teams of 3, a since it would be easier to manage.

**Comment by EthanFalcao** [comment]
Yes, quality or quantity, but i think a 15-person team is too big, to just work on one project. People will learn more if they have a big role on a project.

**Comment by syedshazli** [comment]
That kind of makes sense. But we’d have to make sure more than half the
group is knowledgeable and knows their shit. Or else it’s gonna be the
project manager and a bunch of freshman or something. I’m considering
having people do courses or YouTube tutorials on this stuff before we get
started, since we have a month. Thoughts? I can share the results of the
Google form with you if you want to see experience levels.

**Comment by EthanFalcao** [comment]
Ya, its smart to have the jits do yt tutorials. Also tell the Artem to message me on discor d

**Comment by EthanFalcao** [comment]
Also share the google form with me

**Comment by syedshazli** [comment]
Just sent you collaborator to the form so you can see results. I need to
tell everyone in the form that they have to join the discord too

**Comment by syedshazli** [comment]
Just sent you collaborator to the form so you can see results. I need to
tell everyone in the form that they have to join the discord too. LMK what
yt tutorials you suggest.

**Comment by EthanFalcao** [comment]
i think it would be beneficial if we combine one of the top 2 projects with fingbt

**Comment by syedshazli** [comment]
Yeah maybe. So you think we should have two teams of 7?

**Comment by EthanFalcao** [comment]
ya, we could do that

**Comment by syedshazli** [comment]
Alright bet. I have to prepare for some stuff but after Thursday I should
be free to set things up and get people to do individual projects. I need
to invite all the people who responded to the discord too. Have you got in
contact with Artem yet?

**Comment by EthanFalcao** [comment]
Yes, I was messaging Artem last night

**Pull request closed without merging**
